services:
  mysql:
    image: mysql:9.6.0
    container_name: myapp-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: movies
      MYSQL_USER: movies
      MYSQL_PASSWORD: movies
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: