apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: application

resources:
#  - liquibase-job.yaml

configMapGenerator:
  - name: movies-liquibase-changelog
    files:
      - db.changelog-master.yaml=resources/db/changelog/db.changelog-master.yaml
      - baseline/changelog.yaml=resources/db/changelog/baseline/changelog.yaml
#      - changes/20260315090101-add-rating.yaml=resources/db/changelog/changes/20260315090101-add-rating.yaml
#      - changes/20260318142233-add-index.yaml=resources/db/changelog/changes/20260318142233-add-index.yaml

generatorOptions:
  disableNameSuffixHash: true